export enum GenericDataViewTypes {
  grid = 'grid',
  chart = 'chart',
  number = 'number',
  percent = 'percent',
  text = 'text',
  currency = 'currency',
  piechart = 'piechart',
  boolean = 'boolean',
  link = 'link',
  apps = 'apps',
  photos = 'photos',
  image_upload = 'image-upload',
  map = 'map',
  json = 'json',
  commentry = 'commentry',
  select = 'select',
  file_upload = 'file-upload',
  autocomplete = 'autocomplete',
  progress = 'progress',
  indicator = 'indicator',
  static_text = 'staticText',
  slider = 'slider',
  statistics = 'statistics',
  linechart = 'linechart'
}
